#!/bin/sh

# ----- autostart -----

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
# dunst
/usr/bin/dunst &
# geoclue agent
/usr/lib/geoclue-2.0/demos/agent &
# flameshot
flameshot &
# polybar
${HOME}/.config/polybar/launch.sh &
# check for updates
${HOME}/.local/bin/checkupdate &

# ----- config -----

bspc monitor -d I II III IV V VI VII

bspc config border_radius		8
bspc config border_width        4
bspc config window_gap          12

bspc config top_padding			-5
bspc config bottom_padding		0
bspc config left_padding		0
bspc config right_config		0

bspc config focus_follow_pointer true
bspc config split_ratio			0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# ----- colors -----
. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color8"
bspc config active_border_color "$color13"
bspc config focused_border_color "#96CDFB"
bspc config presel_feedback_color "$color11"

# ----- window rules -----

bspc rule -a *:*:oneko layer=above
bspc rule -a kitty:*:* layer=below
bspc rule -a pavucontrol state=floating follow=on
bspc rule -a timeshift-gtk state=floating follow=on

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

